
builds:
- env:
    - CGO_ENABLED=0

  ldflags:
    - -X "main.version={{.Env.TRAVIS_TAG}}"

  goos:
    - darwin
    - windows
    - linux

archives:
  -
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
