---
routes:
  /v1/foo:
    backend: http://foo:4567
  /v1/bar:
    backend: http://foo:4567
  /v1/static:
    type: static
    backend: http://static:4567
  /v1/ordinal:
    type: ordinal
    backends:
      - http://static:4567
      - http://ordinal:4567
